# Generated by Django 3.0.7 on 2020-06-15 03:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200614_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2020, 6, 15, 3, 13, 43, 438129, tzinfo=utc)),
        ),
    ]
